manifest:
  version: "1.2"

  self:
    path: shared
    west-commands: scripts/west-commands.yml

  remotes:
    - name: origin
      url-base: https://github.com/JaagupAverin
  defaults:
    remote: origin
    revision: main

  projects:
    - name: gale-zephyr
      path: zephyr
      import:
        name-whitelist:
          - hal_espressif
