manifest:
  version: "1.2"

  remotes:
    - name: personal
      url-base: https://github.com/JaagupAverin
  defaults:
    remote: personal
    revision: main

  projects:
    - name: gale-sensor-app
      path: sensor_app
    - name: gale-bluetooth-app
      path: bluetooth_app
    - name: gale-zephyr
      path: zephyr
      import:
        name-whitelist:
          - hal_espressif

  self:
    path: common
    west-commands: scripts/west-commands.yml
